services:
  nginx:
    build:
      context: ./docker/nginx-classic
      dockerfile: Dockerfile.nginx
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      # File docker-compose.yml đã ở trong laravel-app/, nên mount chính folder hiện tại (.) vào /var/www/html
      # Khi container nginx khởi động, nó sẽ sử dụng toàn bộ Laravel app trong folder /var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/nginx-classic
      dockerfile: Dockerfile.php-fpm
    container_name: laravel_php-fpm
    volumes:
      - .:/var/www/html
      # File docker-compose.yml đã ở trong laravel-app/, nên mount chính folder hiện tại (.) vào /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3308
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    command: --default-authentication-plugin=mysql_native_password --port=3308
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3308"
      # Port 3307 là port mà máy host sẽ kết nối tới Container mysql (Port của thông tin connection Dbeaver)
      # Port 3308 là port mà Container mysql sẽ mở ra để kết nối tới máy host
      # => Khi máy host kết nối tới port 3307, nó sẽ kết nối tới port 3308 của Container mysql
      # => Container mysql sẽ mở ra port 3308 để kết nối tới máy host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3308", "-u", "root", "-prootsecret"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: